### ISSUE TITLE
Got RuntimeError by default nnUNet_train CMD

### ISSUE THREAD

**Issue by DISAPPEARED13** [MIC-DKFZ/nnUNet#1043]
I tried to train my dataset with preprocess by nnUNet_verified_and_preprocess, and it work, the next step is to run ```nnUNet_train```, but I got ```RuntimeError``` in return, show that

```Traceback (most recent call last):
  File "/home/hpy13/nnunet/segmentation/bin/nnUNet_train", line 8, in <module>
    sys.exit(main())
  File "/home/hpy13/nnunet/segmentation/lib/python3.6/site-packages/nnunet/run/run_training.py", line 179, in main
    trainer.run_training()
  File "/home/hpy13/nnunet/segmentation/lib/python3.6/site-packages/nnunet/training/network_training/nnUNetTrainerV2.py", line 441, in run_training
    ret = super().run_training()
  File "/home/hpy13/nnunet/segmentation/lib/python3.6/site-packages/nnunet/training/network_training/nnUNetTrainer.py", line 317, in run_training
    super(nnUNetTrainer, self).run_training()
  File "/home/hpy13/nnunet/segmentation/lib/python3.6/site-packages/nnunet/training/network_training/network_trainer.py", line 457, in run_training
    l = self.run_iteration(self.tr_gen, True)
  File "/home/hpy13/nnunet/segmentation/lib/python3.6/site-packages/nnunet/training/network_training/nnUNetTrainerV2.py", line 250, in run_iteration
    l = self.loss(output, target)
  File "/home/hpy13/nnunet/segmentation/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/hpy13/nnunet/segmentation/lib/python3.6/site-packages/nnunet/training/loss_functions/deep_supervision.py", line 39, in forward
    l = weights[0] * self.loss(x[0], y[0])
  File "/home/hpy13/nnunet/segmentation/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/hpy13/nnunet/segmentation/lib/python3.6/site-packages/nnunet/training/loss_functions/dice_loss.py", line 348, in forward
    dc_loss = self.dc(net_output, target, loss_mask=mask) if self.weight_dice != 0 else 0
  File "/home/hpy13/nnunet/segmentation/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/hpy13/nnunet/segmentation/lib/python3.6/site-packages/nnunet/training/loss_functions/dice_loss.py", line 180, in forward
    tp, fp, fn, _ = get_tp_fp_fn_tn(x, y, axes, loss_mask, False)
  File "/home/hpy13/nnunet/segmentation/lib/python3.6/site-packages/nnunet/training/loss_functions/dice_loss.py", line 130, in get_tp_fp_fn_tn
    y_onehot.scatter_(1, gt, 1)
RuntimeError: CUDA error: device-side assert triggered
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/home/hpy13/.conda/envs/hpy132/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/hpy13/.conda/envs/hpy132/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/hpy13/nnunet/segmentation/lib/python3.6/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 92, in results_loop
    raise RuntimeError("Abort event was set. So someone died and we should end this madness. \nIMPORTANT: "
RuntimeError: Abort event was set. So someone died and we should end this madness.
IMPORTANT: This is not the actual error message! Look further up to see what caused the error. Please also check whether your RAM was full

Exception in thread Thread-4:
Traceback (most recent call last):
  File "/home/hpy13/.conda/envs/hpy132/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/hpy13/.conda/envs/hpy132/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/hpy13/nnunet/segmentation/lib/python3.6/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 92, in results_loop
    raise RuntimeError("Abort event was set. So someone died and we should end this madness. \nIMPORTANT: "
RuntimeError: Abort event was set. So someone died and we should end this madness.
IMPORTANT: This is not the actual error message! Look further up to see what caused the error. Please also check whether your RAM was full
```

I didn't change any code in installed nnunet package, and nnUNet version is 1.7.0 the newest one. Why running that with this error?

**Comment by DISAPPEARED13** [comment]
in the first epoch, showing that error log like:

```/pytorch/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:312: operator(): block: [7267,0,0], thread: [0,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.```

is it because that RAM was really full so cannot generate any thread new?

**Comment by DISAPPEARED13** [comment]
I seems solve this problem by re-preprocess my data and check every preprocess output folder, and I found that I used the same index, because ```cropped``` folder is not empty so it used the old data to run train. Problem solved.
 Thanks alot.
