### ISSUE TITLE
Power off and Continuous Label

### ISSUE THREAD

**Issue by FJUNESS** [MIC-DKFZ/nnUNet#1088]
@FabianIsensee Hi, Fabianlsensee!
When it suddenly powered off, I need to restart the training. Is there any easy way to solve the problem?

In addition, when I were training my dataset, the error appeared as below. I am sure that the labels are continuous and 0 is background. Could you please help me to figure it out?  By the way, how to reduce epochs so that I can test my dataset quickly?

```
/pytorch/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:276: operator(): block: [3675,0,0], thread: [55,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:276: operator(): block: [3675,0,0], thread: [63,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:276: operator(): block: [3678,0,0], thread: [55,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
Traceback (most recent call last):
  File "/home/fuxinmei/Public/environments/unet/bin/nnUNet_train", line 11, in <module>
    sys.exit(main())
  File "/home/fuxinmei/Public/environments/unet/lib/python3.6/site-packages/nnunet/run/run_training.py", line 151, in main
    trainer.run_training()
  File "/home/fuxinmei/Public/environments/unet/lib/python3.6/site-packages/nnunet/training/network_training/nnUNetTrainerV2.py", line 431, in run_training
    ret = super().run_training()
  File "/home/fuxinmei/Public/environments/unet/lib/python3.6/site-packages/nnunet/training/network_training/nnUNetTrainer.py", line 316, in run_training
    super(nnUNetTrainer, self).run_training()
  File "/home/fuxinmei/Public/environments/unet/lib/python3.6/site-packages/nnunet/training/network_training/network_trainer.py", line 446, in run_training
    l = self.run_iteration(self.tr_gen, True)
  File "/home/fuxinmei/Public/environments/unet/lib/python3.6/site-packages/nnunet/training/network_training/nnUNetTrainerV2.py", line 247, in run_iteration
    l = self.loss(output, target)
  File "/home/fuxinmei/Public/environments/unet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/fuxinmei/Public/environments/unet/lib/python3.6/site-packages/nnunet/training/loss_functions/deep_supervision.py", line 42, in forward
    l += weights[i] * self.loss(x[i], y[i])
  File "/home/fuxinmei/Public/environments/unet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/fuxinmei/Public/environments/unet/lib/python3.6/site-packages/nnunet/training/loss_functions/dice_loss.py", line 348, in forward
    dc_loss = self.dc(net_output, target, loss_mask=mask) if self.weight_dice != 0 else 0
  File "/home/fuxinmei/Public/environments/unet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/fuxinmei/Public/environments/unet/lib/python3.6/site-packages/nnunet/training/loss_functions/dice_loss.py", line 180, in forward
    tp, fp, fn, _ = get_tp_fp_fn_tn(x, y, axes, loss_mask, False)
  File "/home/fuxinmei/Public/environments/unet/lib/python3.6/site-packages/nnunet/training/loss_functions/dice_loss.py", line 129, in get_tp_fp_fn_tn
    y_onehot = y_onehot.cuda(net_output.device.index)
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```

**Comment by Fnu-Mal** [comment]
@FJUNESS Did you figure out a way around this? 
Thanks!

**Comment by yadoyi** [comment]
Is the problem solved?I have the same problem, how can I solve it?

**Comment by FabianIsensee** [comment]
Your labels are probably not consecutive integers or you haveunexpected integer values in your segmentations. Run `nnUNet_plan_and_preprocess` with the `--verify_dataset_integrity` flag
