### ISSUE TITLE
Assertion 'idx_dim >= 0 && idx_dim < index_size && "index out of bounds"' failed

### ISSUE THREAD

**Issue by Radu-Rosu-2A1** [MIC-DKFZ/nnUNet#1230]
Hello,

I am trying to train a network using nnUNet on a custom dataset with 8 classes. On every training attempt, I get the following error (or something very similar) after a certain number of trained epochs (sometimes 30-40 epochs, sometimes over 100 epochs):

```
../aten/src/ATen/native/cuda/ScatterGatherKernel.cu:365: operator(): block: [529,0,0], thread: [95,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
Traceback (most recent call last):
  File "/opt/conda/bin/nnUNet_train", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.8/site-packages/nnunet/run/run_training.py", line 179, in main
    trainer.run_training()
  File "/opt/conda/lib/python3.8/site-packages/nnunet/training/network_training/nnUNetTrainerV2.py", line 440, in run_training
    ret = super().run_training()
  File "/opt/conda/lib/python3.8/site-packages/nnunet/training/network_training/nnUNetTrainer.py", line 317, in run_training
    super(nnUNetTrainer, self).run_training()
  File "/opt/conda/lib/python3.8/site-packages/nnunet/training/network_training/network_trainer.py", line 467, in run_training
    l = self.run_iteration(self.val_gen, False, True)
  File "/opt/conda/lib/python3.8/site-packages/nnunet/training/network_training/nnUNetTrainerV2.py", line 247, in run_iteration
    output = self.network(data)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/nnunet/network_architecture/generic_UNet.py", line 391, in forward
    x = self.conv_blocks_context[d](x)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/nnunet/network_architecture/generic_UNet.py", line 142, in forward
    return self.blocks(x)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/container.py", line 204, in forward
    input = module(input)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/nnunet/network_architecture/generic_UNet.py", line 65, in forward
    x = self.conv(x)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 613, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 608, in _conv_forward
    return F.conv3d(
RuntimeError: cuDNN error: CUDNN_STATUS_MAPPING_ERROR
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.8/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 92, in results_loop
    raise RuntimeError("Abort event was set. So someone died and we should end this madness. \nIMPORTANT: "
RuntimeError: Abort event was set. So someone died and we should end this madness.
IMPORTANT: This is not the actual error message! Look further up to see what caused the error. Please also check whether your RAM was full
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.8/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 92, in results_loop
    raise RuntimeError("Abort event was set. So someone died and we should end this madness. \nIMPORTANT: "
RuntimeError: Abort event was set. So someone died and we should end this madness.
IMPORTANT: This is not the actual error message! Look further up to see what caused the error. Please also check whether your RAM was full
```

I carefully studied the problem and saw in similar issues that the cause could be the fact that the masks contain unexpected numbers or that there is something wrong in dataset.json. However, I checked the integrity of both the set and the json, and this is not the case. 

I also have to mention that during training there is a lot of available RAM memory and that I have run trainings with nnUNet for other datasets on the same server in the past and I haven't had similar problems. Could there be another cause that generates this problem?

Thanks in advance!

**Comment by wybAug05** [comment]
I hava the same problem 

../aten/src/ATen/native/cuda/ScatterGatherKernel.cu:365: operator(): block: [1733,0,0], thread: [23,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/ScatterGatherKernel.cu:365: operator(): block: [1733,0,0], thread: [24,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/ScatterGatherKernel.cu:365: operator(): block: [1733,0,0], thread: [25,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/ScatterGatherKernel.cu:365: operator(): block: [1792,0,0], thread: [88,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/ScatterGatherKernel.cu:365: operator(): block: [1792,0,0], thread: [120,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/ScatterGatherKernel.cu:365: operator(): block: [1732,0,0], thread: [119,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/ScatterGatherKernel.cu:365: operator(): block: [1732,0,0], thread: [120,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/ScatterGatherKernel.cu:365: operator(): block: [1732,0,0], thread: [121,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/ScatterGatherKernel.cu:365: operator(): block: [1732,0,0], thread: [55,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/ScatterGatherKernel.cu:365: operator(): block: [1732,0,0], thread: [56,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/ScatterGatherKernel.cu:365: operator(): block: [1732,0,0], thread: [87,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/ScatterGatherKernel.cu:365: operator(): block: [1732,0,0], thread: [88,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/ScatterGatherKernel.cu:365: operator(): block: [1732,0,0], thread: [89,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.

2022-11-18 01:48:53.943381: 

2022-11-18 01:48:53.943562: 
epoch:  0
2022-11-18 01:57:56.460899: train loss : 0.6602
2022-11-18 01:58:23.174778: validation loss: 0.4077
2022-11-18 01:58:23.175658: Average global foreground Dice: [0.6143, 0.5147, 0.0102, 0.0117, 0.0, 0.0002]
2022-11-18 01:58:23.175790: (interpret this as an estimate for the Dice of the different classes. This is not exact.)
2022-11-18 01:58:26.602836: lr: 0.009982
2022-11-18 01:58:26.607543: This epoch took 572.663920 s

2022-11-18 01:58:26.607610: 
epoch:  1
2022-11-18 02:06:40.208319: train loss : 0.3394
2022-11-18 02:07:03.292286: validation loss: 0.1702
2022-11-18 02:07:03.293121: Average global foreground Dice: [0.7259, 0.5439, 0.1201, 0.2991, 0.0, 0.0]
2022-11-18 02:07:03.316236: (interpret this as an estimate for the Dice of the different classes. This is not exact.)
2022-11-18 02:07:06.607767: lr: 0.009964
2022-11-18 02:07:06.904060: saving checkpoint...
2022-11-18 02:07:08.542957: done, saving took 1.93 seconds
2022-11-18 02:07:08.583446: This epoch took 521.975777 s

2022-11-18 02:07:08.583632: 
epoch:  2
2022-11-18 02:14:50.190064: train loss : 0.1001
Traceback (most recent call last):
  File "/home/21wyx/.conda/envs/nnunet/bin/nnUNet_train", line 8, in <module>
    sys.exit(main())
  File "/home/21wyx/.conda/envs/nnunet/lib/python3.7/site-packages/nnunet/run/run_training.py", line 179, in main
    trainer.run_training()
  File "/home/21wyx/.conda/envs/nnunet/lib/python3.7/site-packages/nnunet/training/network_training/nnUNetTrainerV2.py", line 440, in run_training
    ret = super().run_training()
  File "/home/21wyx/.conda/envs/nnunet/lib/python3.7/site-packages/nnunet/training/network_training/nnUNetTrainer.py", line 317, in run_training
    super(nnUNetTrainer, self).run_training()
  File "/home/21wyx/.conda/envs/nnunet/lib/python3.7/site-packages/nnunet/training/network_training/network_trainer.py", line 467, in run_training
    l = self.run_iteration(self.val_gen, False, True)
  File "/home/21wyx/.conda/envs/nnunet/lib/python3.7/site-packages/nnunet/training/network_training/nnUNetTrainerV2.py", line 247, in run_iteration
    output = self.network(data)
  File "/home/21wyx/.conda/envs/nnunet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/21wyx/.conda/envs/nnunet/lib/python3.7/site-packages/nnunet/network_architecture/generic_UNet.py", line 391, in forward
    x = self.conv_blocks_context[d](x)
  File "/home/21wyx/.conda/envs/nnunet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/21wyx/.conda/envs/nnunet/lib/python3.7/site-packages/nnunet/network_architecture/generic_UNet.py", line 142, in forward
    return self.blocks(x)
  File "/home/21wyx/.conda/envs/nnunet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/21wyx/.conda/envs/nnunet/lib/python3.7/site-packages/torch/nn/modules/container.py", line 204, in forward
    input = module(input)
  File "/home/21wyx/.conda/envs/nnunet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/21wyx/.conda/envs/nnunet/lib/python3.7/site-packages/nnunet/network_architecture/generic_UNet.py", line 65, in forward
    x = self.conv(x)
  File "/home/21wyx/.conda/envs/nnunet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/21wyx/.conda/envs/nnunet/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 613, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/21wyx/.conda/envs/nnunet/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 609, in _conv_forward
    input, weight, bias, self.stride, self.padding, self.dilation, self.groups
RuntimeError: cuDNN error: CUDNN_STATUS_MAPPING_ERROR
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/home/21wyx/.conda/envs/nnunet/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/21wyx/.conda/envs/nnunet/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/21wyx/.conda/envs/nnunet/lib/python3.7/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 92, in results_loop
    raise RuntimeError("Abort event was set. So someone died and we should end this madness. \nIMPORTANT: "
RuntimeError: Abort event was set. So someone died and we should end this madness. 
IMPORTANT: This is not the actual error message! Look further up to see what caused the error. Please also check whether your RAM was full

Exception in thread Thread-4:
Traceback (most recent call last):
  File "/home/21wyx/.conda/envs/nnunet/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/21wyx/.conda/envs/nnunet/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/21wyx/.conda/envs/nnunet/lib/python3.7/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 92, in results_loop
    raise RuntimeError("Abort event was set. So someone died and we should end this madness. \nIMPORTANT: "
RuntimeError: Abort event was set. So someone died and we should end this madness. 
IMPORTANT: This is not the actual error message! Look further up to see what caused the error. Please also check whether your RAM was full

**Comment by LIKP0** [comment]
Hello! I also met similar questions and I find this cound help:
Remember the label should be consecutive integers.
![image](https://user-images.githubusercontent.com/56829276/203268552-8b14dc63-40fa-4289-b7d1-0a926c9a5e8f.png)

**Comment by cuicathy** [comment]
I got the same error. I finally realized that the generated preprocessed images would not be updated if they already existed. However, I developed these files with mistakes at the beginning and they were not corrected. After deleting the generated folders and generating them again, the error disappeared.
