### ISSUE TITLE
Error when running predict_simple.py

### ISSUE THREAD

**Issue by ZEGUK** [MIC-DKFZ/nnUNet#164]
Hi Fabian, thanks for the excellent work. 

I got troubles when I run command:
(base) F:\nnunet-master\nnunet-master\nnunet>python inference/predict_simple.py -i F:\nnunet-master\nnunet-master\nnunet\nnunet_base\nnunet_raw_splitted\Task05_Prostate\imagesTs -o F:\nnunet-master\nnunet-master\nnunet\RESULTS_FOLDER\nnUNet\3d_fullres\Task05_Prostate -t Task05_Prostate -tr nnUNetTrainer -m 3d_fullres

Here is the bug:

THCudaCheck FAIL file=C:\w\1\s\windows\pytorch\torch/csrc/generic/StorageSharing.cpp line=245 error=71 : operation not supported
Traceback (most recent call last):
  File "inference/predict_simple.py", line 146, in <module>
    overwrite_existing=overwrite)
  File "E:\anaconda\lib\site-packages\nnunet\inference\predict.py", line 244, in predict_from_folder
    tta, overwrite_existing=overwrite_existing)
  File "E:\anaconda\lib\site-packages\nnunet\inference\predict.py", line 159, in predict_cases
    for preprocessed in preprocessing:
  File "E:\anaconda\lib\site-packages\nnunet\inference\predict.py", line 96, in preprocess_multithreaded
    pr.start()
  File "E:\anaconda\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "E:\anaconda\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "E:\anaconda\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "E:\anaconda\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
    reduction.dump(process_obj, to_child)
  File "E:\anaconda\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
  File "E:\anaconda\lib\site-packages\torch\multiprocessing\reductions.py", line 232, in reduce_tensor
    event_sync_required) = storage._share_cuda_()
RuntimeError: cuda runtime error (71) : operation not supported at C:\w\1\s\windows\pytorch\torch/csrc/generic/StorageSharing.cpp:245

(base) F:\nnunet-master\nnunet-master\nnunet>Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "E:\anaconda\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "E:\anaconda\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input

(pytorch version:1.2.0    cuda9.2     GPU : GTX 1080Ti)

How can I solve this problem? Any suggestions will be highly appreciated.

Best wishes!

**Comment by FabianIsensee** [comment]
Hi there,
interesting error. This is the first time I see it. 

Googling reveals the following: 
https://discuss.pytorch.org/t/runtimeerror-cuda-runtime-error-71-operation-not-supported-at/40180

https://pytorch.org/docs/stable/notes/windows.html#multiprocessing-error-without-if-clause-protection

I recommend you google these error messages yourself first, especially because it is not caused by nnU-Net code. 
The problem seems to be a missing freeze_support() which is required for windows. nnU-Net only supports Ubuntu officially (we don't have any windows computers here to test things on) :-) But maybe you can still get ti to work.

Best,
Fabian

**Comment by ckswilliams** [comment]
I was able to get past this. I had to really mangle the code and get rid of the multithreading though. Ubuntu would be a lot easier/better. The relevant multithreading code seemed to be in predict.py

**Comment by ZEGUK** [comment]
@FabianIsensee 
Thanks for your reply!
I followed your suggestions but failed to make it work well on windows. So I had to run inference  on Ubuntu and now it works very well on my own data. 

Best,
Zeguk

**Comment by ZEGUK** [comment]
@ckswilliams 
Thanks for your suggestions! I think it a challenging work to get rid of the multithreading currently, at least for me. But  I  will have a try after understanding multithreading :-).

Best,
Zeguk

**Comment by Karol-G** [comment]
For anyone interested in running inference on windows, you need to replace the `preprocess_multithreaded` method  in `predict.py` with your own preprocess method that doesn't use multiprocessing:

```
def preprocess(trainer, list_of_lists, output_files, segs_from_prev_stage=None):
    if segs_from_prev_stage is None:
        segs_from_prev_stage = [None] * len(list_of_lists)

    classes = list(range(1, trainer.num_classes))
    assert isinstance(trainer, nnUNetTrainer)
    q = Queue()
    predict_save_to_queue(trainer.preprocess_patient, q,
                                                         list_of_lists,
                                                         output_files,
                                                         segs_from_prev_stage,
                                                         classes,
                                                         trainer.plans['transpose_forward'])
    item = q.get()
    while item != "end":
        yield item
        item = q.get()
    q.close()
```

Best,
Karol

**Comment by Jun-electrophysiology** [comment]
@Karol-G 
Hi Karol,
I want to run inference on windows. After I copied all your code above to the nnUnet, the code 'predict_save_to_queue()' isn't recognized.  Any trick I can take? Should I import some modules?
I look forward to your reply. Thank you.

Best,
Jun

**Comment by Jun-electrophysiology** [comment]
Hi there,
@Karol-G @FabianIsensee 
I have found the answer. The 'predict_save_to_queue()' should be replaced by 'preprocess_save_to_queue' in the 'preprocess_save_to_queue'. Or, 'def preprocess_save_to_queue()' should be replaced by the name 'predict_save_to_queue'. 
So the final answer to run the predict_simple.py on windows is:

`def preprocess(trainer, list_of_lists, output_files, segs_from_prev_stage=None):
    if segs_from_prev_stage is None:
        segs_from_prev_stage = [None] * len(list_of_lists)

    classes = list(range(1, trainer.num_classes))
    assert isinstance(trainer, nnUNetTrainer)
    q = Queue()
    predict_save_to_queue(trainer.preprocess_patient, q,
                                                         list_of_lists,
                                                         output_files,
                                                         segs_from_prev_stage,
                                                         classes,
                                                         trainer.plans['transpose_forward'])
    item = q.get()
    while item != "end":
        yield item
        item = q.get()
    q.close()`

And, the related code to call the 'preprocess' should have a minor change.

**Comment by FabianIsensee** [comment]
You can also try setting freeze support and the correct start method for Windows and see if it works then:
https://www.pythonforthelab.com/blog/differences-between-multiprocessing-windows-and-linux/

Sicne we do not have Windows workstations to test this on we cannot help you beyond that ;-) Sorry
