### ISSUE TITLE
"RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED" when training nnunetv2

### ISSUE THREAD

**Issue by ManuBN786** [MIC-DKFZ/nnUNet#1981]
I have 2 gpus & I train with command:  'CUDA_VISIBLE_DEVICES=0,1 nnUNetv2_train Dataset006_Lung 3d_lowres 0 -num_gpus 2'

I have cuda 11.8  & pytorch 2.2.1

And I get this error

How to fix this please ?

![Screenshot from 2024-02-29 15-13-11](https://github.com/MIC-DKFZ/nnUNet/assets/16796765/e1e1c9cb-cb7a-4b7d-8d20-d22766283033)

**Comment by ManuBN786** [comment]
Update: I downgraded my cuda to 11.7 .
I installed CUDA 11.7 with cudnn 8.5.0 and torch 2.0.1.
Now it is working fine !!

**Comment by zhaoawen** [comment]
When you encounter this problem, is it after a period of running?

**Comment by ManuBN786** [comment]
> When you encounter this problem, is it after a period of running?

No at the 0th epoch itself.

So I downgraded a CUDA & installed a  few compatible CUDNN versions until one of them worked & the error was gone.
