### ISSUE TITLE
AssertionError: Torch not compiled with CUDA enabled 

### ISSUE THREAD

**Issue by amspsingh04** [MIC-DKFZ/nnUNet#2243]
I am trying to work with nnUNetv2 on a linux server. 
My env has the following configurations:
```
torch 2.3.0
pip 24.0
python 3.9.19
nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Thu_Mar_28_02:18:24_PDT_2024
Cuda compilation tools, release 12.4, V12.4.131
Build cuda_12.4.r12.4/compiler.34097967_0
```
I am working with the MSD dataset on Colon Cancer (Dataset 10). I have converted it to fit the new dataset format as required by nnUNetv2.

I have access to gpus on the server, and thus I run this command:

# Command:

> CUDA_VISIBLE_DEVICES=1 nnUNetv2_train 010 3d_fullres 2 -device 'cuda' -num_gpus 1 -p nnUNetResEncUNetMPlans

## Output:

> Using device: cuda:0
> /home/graduate/shourya/anaconda3/envs/cibilab_nnunet/lib/python3.9/site-packages/torch/amp/grad_scaler.py:131: UserWarning: torch.cuda.amp.GradScaler is enabled, but CUDA is not available.  Disabling.
>   warnings.warn(
> 
> #######################################################################
> Please cite the following paper when using nnU-Net:
> Isensee, F., Jaeger, P. F., Kohl, S. A., Petersen, J., & Maier-Hein, K. H. (2021). nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation. Nature methods, 18(2), 203-211.
> #######################################################################
> 
> 2024-05-29 20:27:40.533413: do_dummy_2d_data_aug: True
> 2024-05-29 20:27:40.535075: Using splits from existing split file: /home/graduate/shourya/nnUNet/nnUNet_preprocessed/Dataset010_Colon/splits_final.json
> 2024-05-29 20:27:40.535457: The split file contains 5 splits.
> 2024-05-29 20:27:40.535565: Desired fold for training: 2
> 2024-05-29 20:27:40.535657: This split has 101 training and 25 validation cases.

## Error log:
```
Traceback (most recent call last):
  File "/home/graduate/shourya/anaconda3/envs/cibilab_nnunet/bin/nnUNetv2_train", line 8, in <module>
    sys.exit(run_training_entry())
  File "/home/graduate/shourya/nnUNet/nnunetv2/run/run_training.py", line 275, in run_training_entry
    run_training(args.dataset_name_or_id, args.configuration, args.fold, args.tr, args.p, args.pretrained_weights,
  File "/home/graduate/shourya/nnUNet/nnunetv2/run/run_training.py", line 211, in run_training
    nnunet_trainer.run_training()
  File "/home/graduate/shourya/nnUNet/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py", line 1351, in run_training
    self.on_train_start()
  File "/home/graduate/shourya/nnUNet/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py", line 895, in on_train_start
    self.initialize()
  File "/home/graduate/shourya/nnUNet/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py", line 210, in initialize
    self.network = self.build_network_architecture(
  File "/home/graduate/shourya/anaconda3/envs/cibilab_nnunet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1173, in to
    return self._apply(convert)
  File "/home/graduate/shourya/anaconda3/envs/cibilab_nnunet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 779, in _apply
    module._apply(fn)
  File "/home/graduate/shourya/anaconda3/envs/cibilab_nnunet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 779, in _apply
    module._apply(fn)
  File "/home/graduate/shourya/anaconda3/envs/cibilab_nnunet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 779, in _apply
    module._apply(fn)
  [Previous line repeated 2 more times]
  File "/home/graduate/shourya/anaconda3/envs/cibilab_nnunet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 804, in _apply
    param_applied = fn(param)
  File "/home/graduate/shourya/anaconda3/envs/cibilab_nnunet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1159, in convert
    return t.to(
  File "/home/graduate/shourya/anaconda3/envs/cibilab_nnunet/lib/python3.9/site-packages/torch/cuda/__init__.py", line 284, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home/graduate/shourya/anaconda3/envs/cibilab_nnunet/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/home/graduate/shourya/anaconda3/envs/cibilab_nnunet/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/home/graduate/shourya/anaconda3/envs/cibilab_nnunet/lib/python3.9/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 125, in results_loop
    raise e
  File "/home/graduate/shourya/anaconda3/envs/cibilab_nnunet/lib/python3.9/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 103, in results_loop
    raise RuntimeError("One or more background workers are no longer alive. Exiting. Please check the "
RuntimeError: One or more background workers are no longer alive. Exiting. Please check the print statements above for the actual error message
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/graduate/shourya/anaconda3/envs/cibilab_nnunet/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/home/graduate/shourya/anaconda3/envs/cibilab_nnunet/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/home/graduate/shourya/anaconda3/envs/cibilab_nnunet/lib/python3.9/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 125, in results_loop
    raise e
  File "/home/graduate/shourya/anaconda3/envs/cibilab_nnunet/lib/python3.9/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 103, in results_loop
    raise RuntimeError("One or more background workers are no longer alive. Exiting. Please check the "
RuntimeError: One or more background workers are no longer alive. Exiting. Please check the print statements above for the actual error message
```

# Certain questions:
1) Have I configured my cuda incorrectly? Why does it use device cuda:0? Should I work it out with someone who has worked on this linux server?
2) It says torch not compiled with CUDA enabled, could you help me fix that?
I have run the planning and preprocessing and have updated the raw and preprocessed dataset as is required, and have used the new plans.
Infact when I use the old plans as well, the same issue arises.

Could you kindly guide me please, thank you.

**Comment by TizMate** [comment]
Hello, I have had the same problem during several days in the newest nnUNet version and the solution was to change the environment variable **nnUNet_compile=False**... This causes the torch.compile to not be used and the training slows down a bit.

**Comment by amspsingh04** [comment]
@TizMate so do I just straight up do 
export nnUNet_compile=False 
in the .bashrc and carry on with it?

**Comment by TizMate** [comment]
1. Yes, try it and tell us how it went. 
2. Yes, it was the same error I think, but cuda seems to be available in your case because of the log "Using device: cuda:0" (was the same for me). For ensuring cuda is available in your system try `nvidia-smi` and it should show you an information interface about your gpus.

**Comment by GregorKoehler** [comment]
Hi @amspsingh04 and @TizMate ,

and first of all thanks for jumping in to help @TizMate!
@amspsingh04 , can you confirm if the suggestion helped resolve your issue?

**Comment by amspsingh04** [comment]
Hi @GregorKoehler , I tried doing all that and the message that CUDA is not available did not arise again
however the rest of the error log stayed the same, and i do not think there was any improvements there

i tried reinstalling pytorch with cuda support, and could independently verify that torch had the necessary cuda and cudnn support, however, for some reason it didn't work here
what i also encountered (strangely only once) was a C99 compilation error which stemmed from some for loop (not sure what, did not document it at that time and never encountered it again?)

**Comment by GregorKoehler** [comment]
Hi @amspsingh04,
can you post the most recent error logs and maybe when you're encountering it?
It might also be worth to check on the GPU memory before the error happens (e.g. via `watch -n 0,1 nvidia-smi`)

**Comment by amspsingh04** [comment]
## tried it when specifying the gpu id


```
(cocade) [shourya@jujube nnUNet_results]$ CUDA_VISIBLE_DEVICES=3 nnUNetv2_train 010 3d_fullres 4 -device cuda -num_gpus 1 -p nnUNetResEncUNetLPlans
Using device: cuda:0

#######################################################################
Please cite the following paper when using nnU-Net:
Isensee, F., Jaeger, P. F., Kohl, S. A., Petersen, J., & Maier-Hein, K. H. (2021). nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation. Nature methods, 18(2), 203-211.
#######################################################################

2024-06-05 14:50:19.153354: do_dummy_2d_data_aug: True
2024-06-05 14:50:19.154517: Using splits from existing split file: /home/graduate/shourya/nnUNet/nnUNet_preprocessed/Dataset010_Colon/splits_final.json
2024-06-05 14:50:19.154794: The split file contains 5 splits.
2024-06-05 14:50:19.154859: Desired fold for training: 4
2024-06-05 14:50:19.154912: This split has 101 training and 25 validation cases.
using pin_memory on device 0
Exception in thread Thread-1 (results_loop):
Traceback (most recent call last):
  File "/home/graduate/shourya/anaconda3/envs/cocade/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/home/graduate/shourya/anaconda3/envs/cocade/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/home/graduate/shourya/anaconda3/envs/cocade/lib/python3.11/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 125, in results_loop
    raise e
  File "/home/graduate/shourya/anaconda3/envs/cocade/lib/python3.11/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 103, in results_loop
    raise RuntimeError("One or more background workers are no longer alive. Exiting. Please check the "
RuntimeError: One or more background workers are no longer alive. Exiting. Please check the print statements above for the actual error message
Traceback (most recent call last):
  File "/home/graduate/shourya/anaconda3/envs/cocade/bin/nnUNetv2_train", line 8, in <module>
    sys.exit(run_training_entry())
             ^^^^^^^^^^^^^^^^^^^^
  File "/home/graduate/shourya/nnUNet/nnunetv2/run/run_training.py", line 275, in run_training_entry
    run_training(args.dataset_name_or_id, args.configuration, args.fold, args.tr, args.p, args.pretrained_weights,
  File "/home/graduate/shourya/nnUNet/nnunetv2/run/run_training.py", line 211, in run_training
    nnunet_trainer.run_training()
  File "/home/graduate/shourya/nnUNet/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py", line 1362, in run_training
    self.on_train_start()
  File "/home/graduate/shourya/nnUNet/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py", line 903, in on_train_start
    self.dataloader_train, self.dataloader_val = self.get_dataloaders()
                                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/graduate/shourya/nnUNet/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py", line 696, in get_dataloaders
    _ = next(mt_gen_train)
        ^^^^^^^^^^^^^^^^^^
  File "/home/graduate/shourya/anaconda3/envs/cocade/lib/python3.11/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 196, in __next__
    item = self.__get_next_item()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/graduate/shourya/anaconda3/envs/cocade/lib/python3.11/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 181, in __get_next_item
    raise RuntimeError("One or more background workers are no longer alive. Exiting. Please check the "
RuntimeError: One or more background workers are no longer alive. Exiting. Please check the print statements above for the actual error message
```

## funnily enough i ran it right after seeing your notification, and it worked out back then haha

```
(cocade) [shourya@jujube nnUNet]$     CUDA_VISIBLE_DEVICES=2 nnUNetv2_train 010 3d_fullres 3 -device cuda -num_gpus 1 -p nnUNetResEncUNetLPlans
Using device: cuda:0

#######################################################################
Please cite the following paper when using nnU-Net:
Isensee, F., Jaeger, P. F., Kohl, S. A., Petersen, J., & Maier-Hein, K. H. (2021). nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation. Nature methods, 18(2), 203-211.
#######################################################################

2024-06-05 06:06:35.132722: do_dummy_2d_data_aug: True
2024-06-05 06:06:35.133740: Creating new 5-fold cross-validation split...
2024-06-05 06:06:35.135798: Desired fold for training: 3
2024-06-05 06:06:35.135877: This split has 101 training and 25 validation cases.
using pin_memory on device 0
using pin_memory on device 0
/home/graduate/shourya/anaconda3/envs/cocade/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "

This is the configuration used by this training:
Configuration name: 3d_fullres
 {'data_identifier': 'nnUNetPlans_3d_fullres', 'preprocessor_name': 'DefaultPreprocessor', 'batch_size': 2, 'patch_size': [80, 256, 256], 'median_image_size_in_voxels': [150.0, 512.0, 512.0], 'spacing': [3.0, 0.78125, 0.78125], 'normalization_schemes': ['CTNormalization'], 'use_mask_for_norm': [False], 'resampling_fn_data': 'resample_data_or_seg_to_shape', 'resampling_fn_seg': 'resample_data_or_seg_to_shape', 'resampling_fn_data_kwargs': {'is_seg': False, 'order': 3, 'order_z': 0, 'force_separate_z': None}, 'resampling_fn_seg_kwargs': {'is_seg': True, 'order': 1, 'order_z': 0, 'force_separate_z': None}, 'resampling_fn_probabilities': 'resample_data_or_seg_to_shape', 'resampling_fn_probabilities_kwargs': {'is_seg': False, 'order': 1, 'order_z': 0, 'force_separate_z': None}, 'architecture': {'network_class_name': 'dynamic_network_architectures.architectures.unet.ResidualEncoderUNet', 'arch_kwargs': {'n_stages': 7, 'features_per_stage': [32, 64, 128, 256, 320, 320, 320], 'conv_op': 'torch.nn.modules.conv.Conv3d', 'kernel_sizes': [[1, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3]], 'strides': [[1, 1, 1], [1, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2], [1, 2, 2]], 'n_blocks_per_stage': [1, 3, 4, 6, 6, 6, 6], 'n_conv_per_stage_decoder': [1, 1, 1, 1, 1, 1], 'conv_bias': True, 'norm_op': 'torch.nn.modules.instancenorm.InstanceNorm3d', 'norm_op_kwargs': {'eps': 1e-05, 'affine': True}, 'dropout_op': None, 'dropout_op_kwargs': None, 'nonlin': 'torch.nn.LeakyReLU', 'nonlin_kwargs': {'inplace': True}, 'deep_supervision': True}, '_kw_requires_import': ['conv_op', 'norm_op', 'dropout_op', 'nonlin']}, 'batch_dice': False} 

These are the global plan.json settings:
 {'dataset_name': 'Dataset010_Colon', 'plans_name': 'nnUNetResEncUNetLPlans', 'original_median_spacing_after_transp': [5.0, 0.78125, 0.78125], 'original_median_shape_after_transp': [95, 512, 512], 'image_reader_writer': 'SimpleITKIO', 'transpose_forward': [0, 1, 2], 'transpose_backward': [0, 1, 2], 'experiment_planner_used': 'nnUNetPlannerResEncL', 'label_manager': 'LabelManager', 'foreground_intensity_properties_per_channel': {'0': {'max': 445.0, 'mean': 67.2009506225586, 'median': 67.0, 'min': -848.0, 'percentile_00_5': -40.0, 'percentile_99_5': 188.0, 'std': 37.13160705566406}}} 

2024-06-05 06:06:53.092651: unpacking dataset...
2024-06-05 06:07:44.389753: unpacking done...
2024-06-05 06:07:44.393629: Unable to plot network architecture:
2024-06-05 06:07:44.393778: No module named 'hiddenlayer'
2024-06-05 06:07:44.998203: 
2024-06-05 06:07:44.998992: Epoch 0
2024-06-05 06:07:44.999924: Current learning rate: 0.01
2024-06-05 06:12:56.272414: train_loss 0.0581
2024-06-05 06:12:56.274299: val_loss 0.0303
2024-06-05 06:12:56.274615: Pseudo dice [0.0]
2024-06-05 06:12:56.275069: Epoch time: 311.29 s
2024-06-05 06:12:56.275322: Yayy! New best EMA pseudo Dice: 0.0
2024-06-05 06:12:59.849988: 
2024-06-05 06:12:59.850250: Epoch 1
2024-06-05 06:12:59.850586: Current learning rate: 0.00999
2024-06-05 06:17:36.559851: train_loss 0.0123
2024-06-05 06:17:36.560967: val_loss 0.0127
2024-06-05 06:17:36.561114: Pseudo dice [0.0]
2024-06-05 06:17:36.561253: Epoch time: 276.71 s
2024-06-05 06:17:38.419291: 
2024-06-05 06:17:38.419646: Epoch 2
2024-06-05 06:17:38.419930: Current learning rate: 0.00998
2024-06-05 06:22:17.087424: train_loss -0.0064
2024-06-05 06:22:17.088017: val_loss -0.024
2024-06-05 06:22:17.088272: Pseudo dice [0.0]
2024-06-05 06:22:17.088470: Epoch time: 278.67 s
2024-06-05 06:22:18.721854: 
2024-06-05 06:22:18.722113: Epoch 3
2024-06-05 06:22:18.722369: Current learning rate: 0.00997
2024-06-05 06:26:58.238588: train_loss -0.0356
2024-06-05 06:26:58.239262: val_loss -0.0517
2024-06-05 06:26:58.239490: Pseudo dice [0.0]
2024-06-05 06:26:58.239677: Epoch time: 279.52 s
2024-06-05 06:26:59.800519: 

```

do check it out and let me know if i can do something to improve the situation

**Comment by GregorKoehler** [comment]
Hi @amspsingh04,
if I interpret the error logs correctly, I suspect that something might be off with your dataset. When preprocessing, did you use the [--verify_dataset_integrity](https://github.com/MIC-DKFZ/nnUNet/blob/75c46fe7c1c85c60e020d76e387772c7be02a1af/nnunetv2/experiment_planning/plan_and_preprocess_entrypoints.py#L121C12-L121C24) flag?

**Comment by amspsingh04** [comment]
Hi @GregorKoehler i did verify the dataset integrity

I recently stumbled upon an article by fabian and implemented the following to get it to work:

> reduce the number of background workers: use -tl and -tf in nnUNet_plan_and_preprocess (you may have to
go as low as 1!). Reduce the number of workers used by nnUNet_predict by reducing --num_threads_preprocessing and
--num_threads_nifti_save.
> If even -tf 1 during preprocessing is not low enough, consider adding a swap partition located on an SSD.
> upgrade your RAM! (32 GB should get the job done)

https://gitlab.inria.fr/amasson/nnunet/-/blob/d39337eabc3263dc40c5bf3251eb2c44c73113b2/documentation/common_problems_and_solutions.md

**Comment by GregorKoehler** [comment]
Hi @amspsingh04,

great to hear that you could resolve your issue! Can you maybe share the amount of RAM on the machine where you encountered this error?

**Comment by amspsingh04** [comment]
the gpu was a 3090 with 24GB ram, and that's one reason I'm not sure why background workers kept getting killed

**Comment by GregorKoehler** [comment]
Hi @amspsingh04, 
I was referring to your System RAM, not the GPU memory. For the solution you posted, the demands on the system memory are affected, not the GPU memory, see:

> If there is no error message, this could mean that your OS silently killed a background worker because it was about
> to go out of memory. In this case, please rerun whatever command you have been running and closely monitor your system RAM (not GPU memory!) usage.

**Comment by amspsingh04** [comment]
the system ram was 16GB @GregorKoehler, sorry for having misinterpreted your question

**Comment by GregorKoehler** [comment]
Hi @amspsingh04,

your system RAM probably explains the issue you were facing - nnUNet can be quite memory intensive if you're having too many background workers.
Since the issue is resolved, I'm closing this issue.

**Comment by KeruZheng** [comment]
> Hi @GregorKoehler i did verify the dataset integrity
> 
> I recently stumbled upon an article by fabian and implemented the following to get it to work:
> 
> > reduce the number of background workers: use -tl and -tf in nnUNet_plan_and_preprocess (you may have to
> > go as low as 1!). Reduce the number of workers used by nnUNet_predict by reducing --num_threads_preprocessing and
> > --num_threads_nifti_save.
> > If even -tf 1 during preprocessing is not low enough, consider adding a swap partition located on an SSD.
> > upgrade your RAM! (32 GB should get the job done)
> 
> https://gitlab.inria.fr/amasson/nnunet/-/blob/d39337eabc3263dc40c5bf3251eb2c44c73113b2/documentation/common_problems_and_solutions.md

excuse me， could you please tell me how to achieve the above command SOS, really really really appreciate for your help, thanks a looooooot

**Comment by KeruZheng** [comment]
my traceback like this: Traceback (most recent call last):
  File "/data_lg/keru/nnUNet_env/bin/nnUNetv2_train", line 8, in <module>
    sys.exit(run_training_entry())
  File "/data_lg/keru/nnUNet_env/lib/python3.10/site-packages/nnunetv2/run/run_training.py", line 275, in run_training_entry
    run_training(args.dataset_name_or_id, args.configuration, args.fold, args.tr, args.p, args.pretrained_weights,
  File "/data_lg/keru/nnUNet_env/lib/python3.10/site-packages/nnunetv2/run/run_training.py", line 211, in run_training
    nnunet_trainer.run_training()
  File "/data_lg/keru/nnUNet_env/lib/python3.10/site-packages/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py", line 1362, in run_training
    self.on_train_start()
  File "/data_lg/keru/nnUNet_env/lib/python3.10/site-packages/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py", line 906, in on_train_start
    self.initialize()
  File "/data_lg/keru/nnUNet_env/lib/python3.10/site-packages/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py", line 217, in initialize
    ).to(self.device)
  File "/data_lg/keru/nnUNet_env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1340, in to
    return self._apply(convert)
  File "/data_lg/keru/nnUNet_env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 900, in _apply
    module._apply(fn)
  File "/data_lg/keru/nnUNet_env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 900, in _apply
    module._apply(fn)
  File "/data_lg/keru/nnUNet_env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 900, in _apply
    module._apply(fn)
  [Previous line repeated 4 more times]
  File "/data_lg/keru/nnUNet_env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 927, in _apply
    param_applied = fn(param)
  File "/data_lg/keru/nnUNet_env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1326, in convert
    return t.to(
  File "/data_lg/keru/nnUNet_env/lib/python3.10/site-packages/torch/cuda/__init__.py", line 310, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
Exception in thread Thread-2 (results_loop):
Traceback (most recent call last):
  File "/data_lg/keru/nnUNet_env/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/data_lg/keru/nnUNet_env/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/data_lg/keru/nnUNet_env/lib/python3.10/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 125, in results_loop
    raise e
  File "/data_lg/keru/nnUNet_env/lib/python3.10/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 103, in results_loop
    raise RuntimeError("One or more background workers are no longer alive. Exiting. Please check the "
RuntimeError: One or more background workers are no longer alive. Exiting. Please check the print statements above for the actual error message
Exception in thread Thread-1 (results_loop):
Traceback (most recent call last):
  File "/data_lg/keru/nnUNet_env/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/data_lg/keru/nnUNet_env/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/data_lg/keru/nnUNet_env/lib/python3.10/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 125, in results_loop
    raise e
  File "/data_lg/keru/nnUNet_env/lib/python3.10/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 103, in results_loop
    raise RuntimeError("One or more background workers are no longer alive. Exiting. Please check the "
RuntimeError: One or more background workers are no longer alive. Exiting. Please check the print statements above for the actual error message 
![image](https://github.com/user-attachments/assets/bd239a9c-45bd-4a97-ad69-21cec1ec1c9f)
and my service is A6000,thank a lot!!
