### ISSUE TITLE
Does the nnunet adapting GPU memory by the spatial GPU?

### ISSUE THREAD

**Issue by yl255** [MIC-DKFZ/nnUNet#30]
Hi Fabian,
Your paper said as follows:
  All U-Nets are configured to optimally use 12GB Nvidia TitanX GPUs. There is currently no way of adapting to smaller or larger GPUs.
I think that mean, the nnunet using the most memory is 12G.

When I use 24G Nvidia Titan RTX GPU to train the  Task10_Colon data, but the nnunet said: 
    RuntimeError: CUDA out of memory. Tried to allocate 5.63 GiB (GPU 0; 23.76 GiB total capacity; 17.47 GiB already allocated; 5.50 GiB free; 155.50 KiB cached)
I had turned the GPU to the TCC model.
What should I do to resolve this problem?
best,
Yaliang :)

**Comment by FabianIsensee** [comment]
Hi,
you need 12 GB VRAM to be free on your GPU. If you have other things running it will not work. Make sure enough VRAM is available via nvidia-smi.

If you use nnUNet without modifications on your Titan RTX it should just work. With larger cards (I am sometimes using V100 32GB) pytorch will allocate more than 12GB VRAM (like 12.5 or so). But that shouls not be a problem.

Best,
Fabian

**Comment by yl255** [comment]
Hi,
Thank you for your reply.
I just run the code on Windows 10. It is a strange problem.
I will try it on the Ubuntu.
Best,
Yaliang

**Comment by yl255** [comment]
Hi Fabian,
I found the problem on the Windows, why the gpu memory is much more than 12G.
The numpy array use the data type is int32 on the Windows,  when run the code like 'numpy.prod(128,128,128)' the result will be overflow, so the gpu memory will be wrong. 

Best,
Yaliang

**Comment by FabianIsensee** [comment]
Hi,
please reopen an issue if it is still there, otherwise I may not find your posts :-)
Windows is not supported officially because I can't test on Windows. I can try to make it work though. If you well me where these issues occur please let me know and I can try to fix them.
Best,
Fabian

**Comment by FabianIsensee** [comment]
I added dtype=np.int64 to all np.prod. Please check if it works now
Best,
Fabian

**Comment by yl255** [comment]
Hi,
Now I am still trianing the 'liver data' on Windows, hope it can get the right result.
And I will test nnunet with our data. If it work well, I will tell you, but it will take a long time. :(
The code run on Windows, I made some changes as follows:
1. The Windows path delimiter is '\', so the function 'maybe_mkdir_p' will not work well.
2. Maybe it is a problem: the function 'preprocess_multithreaded' in the file pridict.py can not work on my Windows. I do not know what is the problem. So I change it in the main thread.
