### ISSUE TITLE
I use the 2080ti GPU but  CUDA out of memory.

### ISSUE THREAD

**Issue by 2165998** [MIC-DKFZ/nnUNet#337]
Hi, Fabian Isensee.

Thanks for your great work~
I train nnUnet 2d on the Chaos challenge CT modal.
And I resize all the images to 256x256.
In epoch 0,  RuntimeError: CUDA out of memory. Tried to allocate 400.00 MiB (GPU 0; 10.76 GiB total capacity; 9.20 GiB already allocated; 238.75 MiB free; 9.54 GiB reserved in total by PyTorch)
I found the reason is the batch size be set as 50 in the preprocessing step.
So it there any advice on my problem?

Yours,
Xiao

**Comment by 2165998** [comment]
I have solved my problem by using the script "change_batch_size".

**Comment by Barnonewdm** [comment]
Could you indicate where to change batch size?

**Comment by FabianIsensee** [comment]
Have a look here. You can use that snippet: https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/expected_epoch_times.md#how-to-run-the-benchmark

**Comment by 2165998** [comment]
> Could you indicate where to change batch size?

This is a sample code for you~
```
from batchgenerators.utilities.file_and_folder_operations import *
import numpy as np

if __name__ == '__main__':
    input_file = 'yourPath/nnUNet_preprocessed/Task225_CHAOSct/nnUNetPlansv2.1_plans_2D.pkl'
    output_file = 'yourPath/nnUNet_preprocessed/Task225_CHAOSct/nnUNetPlansv2.1_plans_2D.pkl'
    a = load_pickle(input_file)
    print(a['plans_per_stage'][0]['batch_size'])
    a['plans_per_stage'][0]['batch_size'] = int(np.floor(6 / 9 * a['plans_per_stage'][0]['batch_size']))
    print(a['plans_per_stage'][0]['batch_size'])
    save_pickle(a, output_file)
```
