### ISSUE TITLE
DDP distributed.barrier() RuntimeError: CUDA error: out of memory

### ISSUE THREAD

**Issue by jamesben6688** [MIC-DKFZ/nnUNet#593]
I try to run the DDP using your command, while get the following error:

`
rank: 2, memory allocated: 0
rank: 3, memory allocated: 0
rank: 1, memory allocated: 0
done
rank: 0, memory allocated: 0

Traceback (most recent call last):

  File "run/run_training_DDP.py", line 184, in <module>
    main()
  File "run/run_training_DDP.py", line 157, in main
    trainer.initialize(not validation_only)
  File "/afs/crc.nd.edu/user/y/ypeng4/nnUnet/nnunet/training/network_training/nnUNetTrainerV2_DDP.py", line 160, in initialize
    distributed.barrier()
  File "/afs/crc.nd.edu/user/y/ypeng4/.local/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 2420, in barrier
    work = default_pg.barrier(opts=opts)
RuntimeError: CUDA error: out of memory
Killing subprocess 31867
Killing subprocess 31868
Killing subprocess 31869
Killing subprocess 31870
Traceback (most recent call last):
  File "/afs/crc.nd.edu/x86_64_linux/p/pytorch/1.1.0/build/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/afs/crc.nd.edu/x86_64_linux/p/pytorch/1.1.0/build/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/afs/crc.nd.edu/user/y/ypeng4/.local/lib/python3.7/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/afs/crc.nd.edu/user/y/ypeng4/.local/lib/python3.7/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/afs/crc.nd.edu/user/y/ypeng4/.local/lib/python3.7/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/afs/crc.nd.edu/x86_64_linux/p/pytorch/1.1.0/build/bin/python', '-u', 'run/run_training_DDP.py', '--local_rank=3', '3d_fullres', 'nnUNetTrainerV2_DDP', '004', '0', '--dbs']' returned non-zero exit status 1.
`

I have 4 GPUs, batch size on each gpu is set to 2, which will not exceed the GPU memory limit when I don't use DDP. How could this happend?

**Comment by jamesben6688** [comment]
This error disappeared when I changed to another node. So weird.

**Comment by jamesben6688** [comment]
It turns out the background process occupies the GPU memory. I solved it by killing all background processes.
