### ISSUE TITLE
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED

### ISSUE THREAD

**Issue by tommydino93** [MIC-DKFZ/nnUNet#635]
Hi Fabian! Amazing work!

I have been encountering the error:

**RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED**

when running the training with

```
for fold in range(5):
    nnunet_train = ['nnUNet_train', '2d', 'nnUNetTrainerV2', 'Task101_AneurysmDetectionMRA', str(fold), '--npz']
    process = subprocess.Popen(nnunet_train, stdout=subprocess.PIPE)  # pass the list as input to Popen
     _ = process.communicate()[0]  # the [0] is to return just the output, because otherwise it would be outs, errs = 
    process.communicate()
```
In the ../nnUNet_trained_models/nnUNet/2d/Task101_AneurysmDetectionMRA/nnUNetTrainerV2__nnUNetPlansv2.1/fold_0, only 

- debug.json

- training_log_2021_5_11_17_53_32.txt

are created, but not the remaining files.

I installed `nnunet` in a conda environment with `pip install nnunet`, and pytorch in the same environment with `conda install pytorch torchvision torchaudio cudatoolkit=10.2 -c pytorch` which, from what I understood, is the recommended installation for having cudnn included (btw, it is the official one in the [pytorch website](https://pytorch.org/get-started/locally/)). I set all the environment paths and `OMP_NUM_THREADS=1` in the bashrc. I have python 3.8.8.
I already tried once to recreate the conda env from scratch but without success.

I also printed:

```
print(torch.backends.cudnn.enabled)
print(torch.backends.cudnn.version())
```
and got

```
>>> True
>>> 7605
```

Here is the traceback:

```
File "/home/to5743/miniconda3/envs/nnunet/lib/python3.8/site-packages/nnunet/run/run_training.py", line 151, in main
    trainer.run_training()
  File "/home/to5743/miniconda3/envs/nnunet/lib/python3.8/site-packages/nnunet/training/network_training/nnUNetTrainerV2.py", line 431, in run_training
    ret = super().run_training()
  File "/home/to5743/miniconda3/envs/nnunet/lib/python3.8/site-packages/nnunet/training/network_training/nnUNetTrainer.py", line 316, in run_training
    super(nnUNetTrainer, self).run_training()
  File "/home/to5743/miniconda3/envs/nnunet/lib/python3.8/site-packages/nnunet/training/network_training/network_trainer.py", line 446, in run_training
    l = self.run_iteration(self.tr_gen, True)
  File "/home/to5743/miniconda3/envs/nnunet/lib/python3.8/site-packages/nnunet/training/network_training/nnUNetTrainerV2.py", line 245, in run_iteration
    output = self.network(data)
  File "/home/to5743/miniconda3/envs/nnunet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/to5743/miniconda3/envs/nnunet/lib/python3.8/site-packages/nnunet/network_architecture/generic_UNet.py", line 391, in forward
    x = self.conv_blocks_context[d](x)
  File "/home/to5743/miniconda3/envs/nnunet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/to5743/miniconda3/envs/nnunet/lib/python3.8/site-packages/nnunet/network_architecture/generic_UNet.py", line 142, in forward
    return self.blocks(x)
  File "/home/to5743/miniconda3/envs/nnunet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/to5743/miniconda3/envs/nnunet/lib/python3.8/site-packages/torch/nn/modules/container.py", line 119, in forward
    input = module(input)
  File "/home/to5743/miniconda3/envs/nnunet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/to5743/miniconda3/envs/nnunet/lib/python3.8/site-packages/nnunet/network_architecture/generic_UNet.py", line 68, in forward
    return self.lrelu(self.instnorm(x))
  File "/home/to5743/miniconda3/envs/nnunet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/to5743/miniconda3/envs/nnunet/lib/python3.8/site-packages/torch/nn/modules/instancenorm.py", line 57, in forward
    return F.instance_norm(
  File "/home/to5743/miniconda3/envs/nnunet/lib/python3.8/site-packages/torch/nn/functional.py", line 2185, in instance_norm
    return torch.instance_norm(
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED
```

Did you ever encounter this issue? What do you think I could try?

Thanks a lot in advance

**Comment by FabianIsensee** [comment]
Hi,
what GPU are you using? 
We currently recommend to build pytorch yourself, see https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/expected_epoch_times.md
Best,
Fabian

**Comment by tommydino93** [comment]
Hi, thanks for your answer.

I am using an rtx3090 GPU. I could try an rtx2080 and a V100, but I don't think that's the problem.

Now I re-installed pytorch with conda 11.1 as suggested [here](https://pytorch.org/):

conda install pytorch torchvision torchaudio cudatoolkit=11.1 -c pytorch -c nvidia

and indeed when I print

`python -c 'import torch;print(torch.backends.cudnn.version())'`

I now get: `8005`

I launched the job now. Will close this if everything works well

**Comment by FabianIsensee** [comment]
Thanks for the update. Please verify that you are getting the expected epoch times: https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/expected_epoch_times.md

RTX3090 should be roughly on the same level as V100 (a bit faster actually).
Best,
Fabian

**Comment by tommydino93** [comment]
Training times are ok, and the model is now working. Thanks again!
